name: Build & deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        path: 'content/blog'
        repository: ${{ secrets.CONTENT_REPO }}
        token: ${{ secrets.CONTENT_REPO_PAT }}
    - name: Build Gatsby site
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: yarn install
    - run: yarn build
    - run: rm public/*.map
    - run: yarn deploy
    - name: Clear cloudflare cache
      uses: jakejarvis/cloudflare-purge-action@master
    env:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'ap-southeast-2'
      CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
      CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
